<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Isela Marin - PSY150 Final Project Write-Up">
<meta name="dcterms.date" content="2025-01-01">

<title>Does Listening to Music Actually Lower Stress?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Exemplar_WriteUp_Isela_Marin_files/libs/clipboard/clipboard.min.js"></script>
<script src="Exemplar_WriteUp_Isela_Marin_files/libs/quarto-html/quarto.js"></script>
<script src="Exemplar_WriteUp_Isela_Marin_files/libs/quarto-html/popper.min.js"></script>
<script src="Exemplar_WriteUp_Isela_Marin_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Exemplar_WriteUp_Isela_Marin_files/libs/quarto-html/anchor.min.js"></script>
<link href="Exemplar_WriteUp_Isela_Marin_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Exemplar_WriteUp_Isela_Marin_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Exemplar_WriteUp_Isela_Marin_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Exemplar_WriteUp_Isela_Marin_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Exemplar_WriteUp_Isela_Marin_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Does Listening to Music Actually Lower Stress?</h1>
<p class="subtitle lead">A Look at Stress Levels in College Students</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Isela Marin - PSY150 Final Project Write-Up </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">INTRODUCTION</h3>
<p>College students often turn to music as a quick way to relax during stressful times, especially during finals or long study days. We put on our headphones hoping the right playlist will calm us down, but is it actually effective? In this project, I explored the relationship between music listening and daily stress levels among college students. Specifically, I wanted to know whether listening to music for longer periods of time was really associated with feeling less stressed.</p>
<p>My research question was simple: Does the amount of time spent listening to music reduce daily stress levels? This question matters for psychology and students’ wellness because stress is a major factor in academic burnout. Music is one of the most popular, accessible coping tools students use daily. If music truly reduces stress, even a bit, it could offer students an easy way to deal with stress during busy weeks.</p>
<p><strong>My Hypothesis:</strong> Students who listen to more music will have lower stress levels, controlling for age and whether they listened with others.</p>
<hr>
<p>The simulated data used for this analysis was fabricated to reflect a study by Linnemann et al.&nbsp;(2018). For this study a class survey was taken in which 60 college students reported their daily stress levels and music-listening habits. The goal of the study was to capture everyday behaviors rather than lab-based measures. Because the data came from everyday student reports rather than a lab experiment, the findings are especially relatable to college life. At the same time, this also means the data are self-reported and non-experimental, so the results should be interpreted carefully.The survey included questions about how long students listened to music, how calming they thought it was, their age, and whether they listened alone or with others.</p>
<p>The main outcome variable was daily stress level, measured on a scale from 0 to 2.5. The focal predictor was minutes spent listening to music on the day of the survey. I also included age and listening with others as control variables because both could be related to stress separately from time spent listening to music (i.e., music duration).</p>
</section>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">Data source:</h3>
<blockquote class="blockquote">
<p><a href="https://link.springer.com/content/pdf/10.1007/s12529-017-9697-5.pdf">Linnemann et al.&nbsp;(2018) <em>Music Listening and Stress in Daily Life: A Matter of Timing</em></a></p>
</blockquote>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"load_plot_functions.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="read-in-data-update-factor-levels" class="level3">
<h3 class="anchored" data-anchor-id="read-in-data-update-factor-levels">Read in data &amp; update factor levels</h3>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>music_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"music_stress_daily_sim_N60_2.csv"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">with_others =</span> <span class="fu">factor</span>(with_others,                      <span class="co"># RECODE FACTOR</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),                                       <span class="co"># ORDER LEVELS</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Listened Alone"</span>, <span class="st">"Listened With Others"</span>))) <span class="co"># ADD LABELS</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>How many student’s listened to music alone versus with others?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(music_data<span class="sc">$</span>with_others) <span class="co"># CHECK: Did the factor get coded correctly?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> music_data$with_others  n   percent
         Listened Alone 47 0.7833333
   Listened With Others 13 0.2166667</code></pre>
</div>
</div>
<hr>
</section>
<section id="what-the-data-looked-like" class="level3">
<h3 class="anchored" data-anchor-id="what-the-data-looked-like">WHAT THE DATA LOOKED LIKE</h3>
<p>Before running any models, I wanted to see the shape of the variables key to my analysis. Looking at the distribution of the outcome variable is important part of the analysis process to evaluate the regression assumption normality and get a better sense of what the data looks like.</p>
<hr>
</section>
<section id="descriptive-statistics-stress-time-listened-to-music" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics-stress-time-listened-to-music">Descriptive Statistics: Stress &amp; Time Listened to Music</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>music_data <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(stress_level, music_listened_self, age, workload_today) <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    vars  n  mean   sd median trimmed  mad  min   max range
stress_level           1 60  1.05 0.31   1.06    1.05 0.35  0.3  1.73  1.43
music_listened_self    2 60  0.35 0.48   0.00    0.31 0.00  0.0  1.00  1.00
age                    3 60 22.82 3.29  22.50   22.65 3.71 18.0 30.00 12.00
workload_today         4 60  4.53 2.33   5.00    4.48 1.48  0.0 10.00 10.00
                     skew kurtosis   se
stress_level        -0.03    -0.55 0.04
music_listened_self  0.61    -1.65 0.06
age                  0.31    -0.91 0.42
workload_today       0.18    -0.32 0.30</code></pre>
</div>
</div>
</section>
<section id="histogram-plot-most-students-reported-mild-to-moderate-stress-with-no-extreme-outliers" class="level3">
<h3 class="anchored" data-anchor-id="histogram-plot-most-students-reported-mild-to-moderate-stress-with-no-extreme-outliers">Histogram plot: Most students reported mild to moderate stress, with no extreme outliers</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use `hist_plot()` to visualize the distribution of continuous outcomes &amp; predictors</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> music_data,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">binwidth=</span>.<span class="dv">1</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_var =</span> stress_level,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_label =</span> <span class="st">"Daily Stress Scores"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">break_min =</span><span class="dv">0</span>, <span class="at">break_max =</span><span class="fl">2.5</span> , <span class="at">break_by =</span> .<span class="dv">2</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_line =</span> <span class="cn">TRUE</span>, <span class="at">median_line =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">skew_value =</span> <span class="cn">TRUE</span>, <span class="at">kurtosis_value =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">title   =</span> <span class="st">"Distribution of Student Daily Stress Scores"</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram of daily stress levels showed that most students reported mild to moderate stress. The average stress score was about 1.05 and the median was very similar at 1.06, which means the center of the distribution was around 1.1 on the stress scale. The scores ranged from 0.30 to 1.73, so there were no extreme high stress values in this sample. The skew was close to zero, which means the stress scores were fairly balanced on both sides of the mean. Overall, stress looked approximately normal, which is important because stress is the main outcome variable to be used for the regression model analyses.</p>
<hr>
</section>
<section id="histogram-plot-of-music-listening-minutes-were-highly-skewed-most-students-listened-briefly." class="level3">
<h3 class="anchored" data-anchor-id="histogram-plot-of-music-listening-minutes-were-highly-skewed-most-students-listened-briefly.">Histogram plot of Music-listening minutes were highly skewed, most students listened briefly.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> music_data,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">binwidth =</span> <span class="dv">2</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_var =</span> duration_min,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_label =</span> <span class="st">"Minutes Spent Listening to Music (Music Duration)"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="at">fill =</span> <span class="st">"purple"</span>, <span class="at">color =</span> <span class="st">"lightpink"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="at">break_min =</span> <span class="dv">0</span>, <span class="at">break_max =</span> <span class="dv">120</span>, <span class="at">break_by =</span> <span class="dv">10</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="at">mean_line =</span> <span class="cn">TRUE</span>, <span class="at">median_line =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="at">skew_value =</span> <span class="cn">TRUE</span>, <span class="at">kurtosis_value =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Music Duration"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of music listening duration looked very different from the stress scores. Most students listened to music for only a short amount of time (under 10 minutes), but a few students listened for much longer periods, creating a long right tail. The distribution of music duration is positively skewed as shown in the histogram by the long tail pointing to the right. The mean was 16.7 minutes, but the median was only 4.2 minutes, which shows that the average was pulled to the right by a small number of students who listened for a long time. This is important to notice because a “typical” student listened for much less time than the mean suggests.</p>
<hr>
</section>
<section id="histogram-plot-of-students-age" class="level3">
<h3 class="anchored" data-anchor-id="histogram-plot-of-students-age">Histogram plot of Students’ Age</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> music_data,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">binwidth =</span> <span class="dv">1</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_var =</span> age,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_label =</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="at">fill =</span> <span class="st">"purple"</span>, <span class="at">color =</span> <span class="st">"yellow"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="at">break_min =</span> <span class="dv">18</span>, <span class="at">break_max =</span> <span class="dv">30</span>, <span class="at">break_by =</span> <span class="dv">1</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="at">mean_line =</span> <span class="cn">TRUE</span>, <span class="at">median_line =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="at">skew_value =</span> <span class="cn">TRUE</span>, <span class="at">kurtosis_value =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Age of Student's - College Data"</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The sample included students ranging from 18 to 30 years old. The average age was about 23 years, which is the center of the age distribution (<code>M = 22.8, SD = 3.3</code>). The standard deviation was 3.3, meaning most students were within <code>+/- 3</code> years of the average age. The plot also shows that there were many students in the 18–19 age range, but there were still several older students in their mid-to-late twenties. Since age varies across the sample, it makes sense to include it as a control variable in the regression model.</p>
<hr>
</section>
<section id="histogram-plot-of-hours-of-reported-work-study-job-hours" class="level3">
<h3 class="anchored" data-anchor-id="histogram-plot-of-hours-of-reported-work-study-job-hours">Histogram plot of Hours of Reported Work (Study + Job Hours)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist_plot</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> music_data,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">binwidth =</span> <span class="dv">1</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_var =</span> workload_today,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_label =</span> <span class="st">"Hours at Work"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="at">fill =</span> <span class="st">"lightgreen"</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="at">break_min =</span> <span class="dv">0</span>, <span class="at">break_max =</span> <span class="dv">10</span>, <span class="at">break_by =</span> <span class="dv">1</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="at">mean_line =</span> <span class="cn">TRUE</span>, <span class="at">median_line =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="at">skew_value =</span> <span class="cn">TRUE</span>, <span class="at">kurtosis_value =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"How Many Hours Participants Worked/Studied"</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of overall daily workload (employment and study hours) shows that students had a range of work responsibilities. Workload ranged from 0 to 10 hours, with an average of 4.53 hours and a median of 5 hours. This means a typical student reported spending about 4–5 hours working or studying that day. There were also a few students who reported higher workloads around 8–10 hours. This variable is useful to look at because workload could be related to stress, even if it is not the main focus of this project.</p>
<hr>
</section>
<section id="look-at-associations-using-scatterplots" class="level3">
<h3 class="anchored" data-anchor-id="look-at-associations-using-scatterplots">Look at associations using scatterplots</h3>
<hr>
</section>
<section id="scatter-plot-of-stress-scores-by-music-duration" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-of-stress-scores-by-music-duration">Scatter Plot of Stress Scores by Music Duration</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter_plot</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> music_data,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_var =</span> duration_min,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_label =</span> <span class="st">"Music Duration (min)"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y_var =</span> stress_level,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">y_label =</span> <span class="st">"Stress Level Score"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">point_color =</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">corr_line =</span> <span class="cn">TRUE</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">title   =</span> <span class="st">"Duration Listened to Music vs. Stress Levels"</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A small downward trend suggests longer listening may be linked to slightly lower stress (<span class="math inline">\(r = -.21\)</span>).</p>
</section>
<section id="scatter-plot-of-stress-levels-by-age-of-students" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-of-stress-levels-by-age-of-students">Scatter Plot of Stress Levels by Age of Students</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter_plot</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> music_data,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y_var =</span> stress_level, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y_label =</span> <span class="st">"Stress Levels"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_var =</span> age,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_label =</span> <span class="st">"Age"</span>, </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">point_color =</span> <span class="st">"violet"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">corr_line =</span> <span class="cn">TRUE</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">title   =</span> <span class="st">"Student Age and Stress Levels"</span> </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows that for student’s <code>age</code> &amp; <code>stress</code> show a small negative correlation (<span class="math inline">\(r = -.21\)</span>), with stress levels decreasing slightly among older participants in the sample.</p>
<hr>
</section>
<section id="estimate-correlations-significance" class="level3">
<h3 class="anchored" data-anchor-id="estimate-correlations-significance">Estimate correlations &amp; significance</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>music_data <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(stress_level, duration_min, age, workload_today) <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_corr</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">triangle =</span> <span class="st">"lower"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">2</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">stress_level</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">duration_min</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">age</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">workload_today</td>
</tr>
<tr class="even">
<td style="font-style: italic">stress_level</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">duration_min</td>
<td style="text-align: center; padding: 0.2cm;">-0.28<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">age</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.21<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.13<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">workload_today</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.11<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.07<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.09<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td colspan="5" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with listwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The correlation table shows only one significant association with stress scores and the continuous predictors. That is, the minutes of music listened to was negatively correlated with stress (<span class="math inline">\(r = -.28, p &lt; .05\)</span>). Age was also negatively associated with stress and daily workload hours positively associated but both correlations were statistically insignificant.</p>
<hr>
</section>
<section id="examination-of-categorical-predictor" class="level3">
<h3 class="anchored" data-anchor-id="examination-of-categorical-predictor">Examination of Categorical Predictor</h3>
<p>What is the difference in predicted stress scores for students who listened to music with others compared to listening alone <code>with_others</code> (<code>0 = Listened Alone</code>, <code>1 = Listened With Others</code>)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean_diff_barplot</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> music_data, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">outcome =</span> <span class="st">"stress_level"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">group_var =</span> <span class="st">"with_others"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">colors =</span> <span class="fu">c</span>(<span class="st">"cyan"</span>, <span class="st">"aquamarine"</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Is stress different if you listen to music with friends?"</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar plot shows a clear difference in average stress levels between the two groups. Students who listened to music alone had a higher average stress score of 1.13, while students who listened with others had a lower average stress score of 0.77. The mean difference was 0.362 points, meaning students who listened alone reported stress levels about 0.36 points higher than students who listened with others. This suggests that listening with other people may be linked to lower stress, which is why it makes sense to include this variable as a control in the regression model.</p>
<hr>
</section>
<section id="analysis-approach" class="level3">
<h3 class="anchored" data-anchor-id="analysis-approach">ANALYSIS APPROACH</h3>
<p>Based on what I have seen, I came up with my final hypothesis: Students who listened to music for longer duration will report lower stress levels, controlling for age and whether they listened with others. I chose stress as the outcome because it’s an important psychological variable for college students. Music duration was my chosen focal predictor because it captures the amount of exposure to music. Age as well as social listening were included as controls since both could influence stress independently of duration.</p>
<p>Due to the fact that stress levels is a continuous variable, I used a linear regression model, which examines how an outcome variable is associated with a predictor variable while holding control variables constant. I started with a simple regression of the outcome regressed on my main predictor in my hypothesis. Then I added the control variables one-by-one. This strategy is called <em>forward step-wise regression</em>.</p>
</section>
<section id="main-results---regression" class="level3">
<h3 class="anchored" data-anchor-id="main-results---regression">MAIN RESULTS - REGRESSION</h3>
<p>Model 1: Outcome &amp; predictor only</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(stress_level <span class="sc">~</span>  duration_min,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> music_data)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(m1, <span class="at">digits=</span> <span class="dv">3</span>, <span class="at">model.fit =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">stress_level</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
  
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">1.101</td>
<td style="text-align: right;">0.046</td>
<td style="text-align: right;">24.163</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">duration_min</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">-2.202</td>
<td style="text-align: right;">0.032</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: OLS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tab_model(m1,</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># digits = 3,</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># show.se = TRUE,</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># show.ci = TRUE,</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># show.r2 = FALSE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In model-1, the intercept represents the predicted average stress score, <span class="math inline">\(\alpha = 1.101\)</span>, among students who listened to zero minutes of music daily. The coefficient for music duration means that for every additional minute of music listened to the model predicted stress to decrease by .003 points (<span class="math inline">\(\beta_1 = -0.003, p &lt; .05\)</span>). This predictor was statistically significant (<span class="math inline">\(p = .032\)</span>), meaning that there is evidence that minutes spent listening to music is associated with lower stress. However, this association is not necessarily a causal effect. We need to check whether this relationship is confounded by omitted variables. Additionally, since stress was measured on a scale from about 0 to 2.5 in this data, the size of the effect is small, even though it was found to be statistically significant.</p>
<p>Model 2: Add the 1st control variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(stress_level <span class="sc">~</span>  duration_min <span class="sc">+</span> age,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> music_data)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(m2, <span class="at">digits=</span> <span class="dv">3</span>, <span class="at">model.fit =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">stress_level</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
  
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">1.473</td>
<td style="text-align: right;">0.276</td>
<td style="text-align: right;">5.333</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">duration_min</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">-2.021</td>
<td style="text-align: right;">0.048</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">age</td>
<td style="text-align: right;">-0.016</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">-1.365</td>
<td style="text-align: right;">0.178</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: OLS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tab_model(m2,</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># digits = 3,</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># show.se = TRUE,</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># show.ci = FALSE,</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># show.r2 = FALSE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <code>Model-2</code> the intercept now is not interpretable because when we hold all the control variables at zero the model is making a prediction for students with <code>age = 0</code> which is not a meaningful prediction. Interestingly, the coefficient for <code>duration_min</code> stayed approximately the same in terms of magnitude at <span class="math inline">\(- .003\)</span> but the p-value shifted from <span class="math inline">\(p = .032\)</span> in the previous model to <span class="math inline">\(p = .048\)</span>. This means that the relationship is still statistically significant, but only barely below the standard <code>.05</code> cutoff. The coefficient for age is negative, indicating that older students tended to report slightly lower stress levels, but this relationship is not statistically significant (<span class="math inline">\(\beta_2 = -0.016, p = .178\)</span>).</p>
<p>Model 3: Final Model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(stress_level <span class="sc">~</span>  duration_min <span class="sc">+</span> age <span class="sc">+</span> with_others,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> music_data)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(m3, <span class="at">digits=</span> <span class="dv">3</span>, <span class="at">model.fit =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">stress_level</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
 
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">F(3,56)</td>
<td style="text-align: right;">7.674</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">R²</td>
<td style="text-align: right;">0.291</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Adj. R²</td>
<td style="text-align: right;">0.253</td>
</tr>
</tbody>
</table>
</div>
 
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">1.525</td>
<td style="text-align: right;">0.248</td>
<td style="text-align: right;">6.139</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">duration_min</td>
<td style="text-align: right;">-0.002</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">-1.447</td>
<td style="text-align: right;">0.153</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">age</td>
<td style="text-align: right;">-0.016</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">-1.506</td>
<td style="text-align: right;">0.138</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">with_othersListened With Others</td>
<td style="text-align: right;">-0.332</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">-3.824</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: OLS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<p>In the final model, the intercept represents the predicted stress level when all predictors are held at zero. In this model, that means the predicted stress level for a participant who listened to zero minutes of music (<code>duration_min = 0</code>), listened alone, and had an age of zero. Since <code>age = 0</code> is not a realistic value, the intercept is not substantively meaningful on its own. However, we still use the intercept as part of the regression equation to calculate predictions by inputting realistic values of age and music duration.</p>
<p>The predictor coefficient estimated for listening to music changed from statistically significant in <code>Model-2</code> to insignificant in <code>Model-3</code>. The coefficient is still small and negative, but now it is not significant (<span class="math inline">\(\beta_1 = -0.002, p = .153\)</span>). This means that students who listened to more minutes of music had slightly lower predicted stress, but after controlling for age and whether they listened with others, there was not strong evidence that music duration reliably predicted stress. In other words, the relationship between music duration and stress became weaker once the social listening variable was added.</p>
<p>The additional covariate comparing students who listened with others versus students who listened alone was statistically significant (<span class="math inline">\(\beta_3 = -0.332, p &lt; .001\)</span>). Notably, students who listened to music with others had predicted stress scores about .332 points lower than students who listened alone, holding music duration and age constant. This suggests that the social side of music listening may matter more for stress than simply the number of minutes spent listening.</p>
<p>Compare regression results across <code>Model-1</code>, <code>Model-2</code>, and <code>Model-3</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(m1, m2, m3,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="at">dv.labels =</span> <span class="fu">c</span>(<span class="st">"Model-1"</span>, <span class="st">"Model-2"</span>, <span class="st">"Model-3"</span>),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="at">show.se =</span> <span class="cn">TRUE</span>, <span class="at">show.ci =</span> <span class="cn">FALSE</span>, <span class="at">show.r2 =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Model-1</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Model-2</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Model-3</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">std. Error</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">std. Error</td>
<td style="text-align: center;">p</td>
<td style="text-align: center;">Estimates</td>
<td style="text-align: center;">std. Error</td>
<td style="text-align: center;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.101</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.046</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.473</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.276</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
<td style="text-align: center;">1.525</td>
<td style="text-align: center;">0.248</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">duration min</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.003</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.001</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.032</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.003</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.001</td>
<td style="text-align: center;"><strong>0.048</strong></td>
<td style="text-align: center;">-0.002</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">0.153</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">age</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.016</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.012</td>
<td style="text-align: center;">0.178</td>
<td style="text-align: center;">-0.016</td>
<td style="text-align: center;">0.011</td>
<td style="text-align: center;">0.138</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">with others [Listened<br>
With Others]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.332</td>
<td style="text-align: center;">0.087</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">60</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">60</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">60</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Across Models 1-3, the relationship between music duration and stress stayed in the expected direction, meaning more music listening was still associated with slightly lower stress. However, the relationship became weaker after adding the control variables. Music duration was significant in Model-1 and just barely significant in Model-2, but it was no longer significant in Model-3 after adding whether students listened alone or with others. This suggests that how students listened to music may matter more than simply how many minutes they listened.</p>
<hr>
</section>
<section id="making-sense-of-the-results" class="level3">
<h3 class="anchored" data-anchor-id="making-sense-of-the-results">MAKING SENSE OF THE RESULTS</h3>
<p>The main question was whether music duration predicted stress. The coefficient for duration in my final model was -0.002, which means that each additional minute of music listening was associated with a very small decrease in predicted stress. However, the p-value was 0.153, which is above the usual 0.05 cutoff. This means the relationship was not statistically significant in the final model. In this sample, I do not have strong evidence that listening to music for longer periods reliably predicted lower stress after controlling for age and whether students listened alone or with others.</p>
<p>The most interesting pattern was actually the “listening with others” variable. Students who listened with others had predicted stress levels about 0.332 points lower than students who listened alone, and this result was statistically significant. This suggests that maybe the social side of music matters more than the number of minutes. That feels believable to me because music is often tied to shared experiences like driving with friends, singing together, or just feeling less alone. This result makes sense to me because we as humans are social creatures, and sometimes the company of someone else can lift our spirits more than the music itself.</p>
<hr>
</section>
<section id="test-regression-assumptions-model-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="test-regression-assumptions-model-diagnostics">Test Regression Assumptions (Model Diagnostics)</h3>
<ul>
<li>Assumption 1: Normality of residuals</li>
<li>Assumption 2: Homoscedasticity</li>
<li>Assumption 3: Linerity</li>
</ul>
<p><strong>Assumption 1:</strong> Test Normality Assumption using a ‘qq-plot’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check_normality</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I checked the normality of the residuals using a QQ plot. A QQ plot shows whether the model’s errors are roughly normally distributed. In this plot, most of the points fall very close to the reference line, with only small deviations at the ends. This suggests that the residuals are approximately normal. Overall, the normality assumption appears to be met, which supports the use of the linear regression model.</p>
<p><strong>Assumption 2:</strong> Test Homogeneity Assumption</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check_heteroskedasticity</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I also checked the homogeneity of variance assumption, which means that the spread of the residuals should be fairly similar across the range of predicted values. The plot does not show a strong funnel shape, which is a good sign. However, the line is not perfectly flat, and there is some unevenness in the spread of residuals. Since the residual spread is a little uneven across fitted values, it suggests that the model has some heteroskedasticity. Because of this, I would not say the assumption is perfectly met, but there does not appear to be a major violation.</p>
<p><strong>Assumption 3:</strong> Test Linearity Assumption</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check_model</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exemplar_WriteUp_Isela_Marin_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, I checked the linearity assumption using the residuals vs.&nbsp;fitted plot. This plot helps show whether the relationship between the predictors and stress is reasonably linear. The line is mostly close to horizontal, although it is not perfectly flat. There is also some clustering of points, which makes sense because the model includes a categorical variable for whether students listened alone or with others. Overall, I do not see a strong curved pattern, so the linearity assumption appears mostly reasonable.</p>
<p><strong>Summary of Regression Tests</strong>:</p>
<p>Altogether, the regression diagnostics suggest that the linear regression model is appropriate enough for interpreting the results. The residuals appear approximately normal, there is no major funnel shape in the residual spread, and the linearity plot does not show strong curvature. The assumptions are not perfect, especially for homogeneity of variance, but there are no major red flags that would make me reject the model. This means the estimated coefficients can be interpreted, but the results should still be discussed carefully because the sample is small and the data are observational.</p>
<hr>
</section>
<section id="implications-limitations" class="level3">
<h3 class="anchored" data-anchor-id="implications-limitations">IMPLICATIONS, &amp; LIMITATIONS</h3>
<p>Overall, the results did not strongly support my original hypothesis. While the direction of the effect matched the expectations which was, more music listening was associated with slightly lower stress, the size was extremely small and not statistically significant. One possible explanation is that how students listen to music matters more than how long they listen for. Duration may not capture emotional engagement, genre, or purpose (relaxing, to cry to, background noise, etc). Another explanation is that stress is influenced by external factors that weren’t measured in this dataset.</p>
<p>There are a few limitations worth noting. The data did come from self-reports, which can be imprecise. The sample size was relatively small (N= 60), which reduces the ability to detect subtle relationships. Due to the fact that this was a correlational survey, no causal claims can be made, meaning that we cannot say for sure that listening to music causes less stress. Despite these limitations, the project raises interesting questions about how students use music to regulate emotions. A future study might measure emotional engagement with music or even examine different genres to see whether certain types of music are more effective for stress reduction.</p>
<p>In the end, longer music listening did not significantly predict lower stress among college students in this study. However, listening with others showed a small trend toward lower stress, suggesting that social experience of music may matter more than duration. These results remind us that stress is complex, and while music may help, it is just one piece of a very large puzzle for student well-being. Overall, this study suggests that how we engage with music, emotionally or socially, may play a bigger role in stress relief than simply how long we listen.</p>
<hr>
</section>
<section id="practice-rendering" class="level3">
<h3 class="anchored" data-anchor-id="practice-rendering">Practice rendering!</h3>
<blockquote class="blockquote">
<p>(Extra Credit Opportunity for Final Project Submission)</p>
</blockquote>
<ol type="1">
<li>Review your script for typos, rendering will only work when all the code is correct!</li>
<li>Click the <code>Render</code> option in the menu bar at the top of your script.</li>
<li>If an <strong>error message</strong> shows up in the terminal read it! It will provide the line number where the render failed.</li>
<li>Keep rendering unit you catch all the typos!</li>
<li>Once your document renders successfully, open the <code>HTML</code> file in the <code>web browser</code> to make sure your writing, tables, and plots all appear correctly.</li>
<li>To submit this rendered file right-click on the web-page and choose <code>Print</code>. Next choose the option <code>Save as PDF</code>. Submit the saved PDF file to receive extra credit!</li>
</ol>
<hr>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>